# Test-support script (not installed): drives `mine --interactive` through a
# piped stdin and pins what a user sees. Required: -DHELPMATE -DTABLES -DSESSION
foreach(v HELPMATE TABLES SESSION)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "verify_mine_shell.cmake: -D${v}=... is required")
  endif()
endforeach()
set(out_json "${TABLES}/shell_out.json")
file(REMOVE "${out_json}")
file(READ "${SESSION}" script)
string(REPLACE "@OUT@" "${out_json}" script "${script}")
file(WRITE "${TABLES}/shell_session.txt" "${script}")

execute_process(COMMAND "${HELPMATE}" mine KQvk --dtm 2 --max infinity --interactive --tables "${TABLES}"
                INPUT_FILE "${TABLES}/shell_session.txt"
                OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "shell exited ${rc}:\n${out}\n${err}")
endif()
foreach(p "loaded 580 positions \\(KQvk dtm=2\\)" "\\[580\\] mine> " "\\[477\\] mine> " "\\[257\\] mine> ")
  if(NOT "${err}" MATCHES "${p}")
    message(FATAL_ERROR "stderr lacks ${p}:\n${err}")
  endif()
endforeach()
# stdout, in order: narrowing tallies, histogram, back, list, show, save.
if(NOT "${out}" MATCHES "^477 positions\n257 positions\n")
  message(FATAL_ERROR "tallies wrong:\n${out}")
endif()
if(NOT "${out}" MATCHES "\nmirror +257\n")
  message(FATAL_ERROR "histogram lacks mirror 257:\n${out}")
endif()
if(NOT "${out}" MATCHES "\n477 positions\n     1  8/8/8/8/8/8/8/k1KQ4 b - - 0 1\n     2  ")
  message(FATAL_ERROR "back/list wrong:\n${out}")
endif()
if(NOT "${out}" MATCHES "\n8/8/8/8/8/8/8/k1KQ4 b - - 0 1\n  themes:[^\n]*mirror[^\n]*\n  Ka2 Qa4#\n")
  message(FATAL_ERROR "show wrong:\n${out}")
endif()
if(NOT "${out}" MATCHES "saved 477 positions to [^\n]*shell_out.json \\(json, themes\\)\n$")
  message(FATAL_ERROR "save line wrong or something ran after quit:\n${out}")
endif()
if(NOT EXISTS "${out_json}")
  message(FATAL_ERROR "save did not write ${out_json}")
endif()
file(READ "${out_json}" saved)
if(NOT "${saved}" MATCHES "\"positions\"" OR NOT "${saved}" MATCHES "\"themes\"")
  message(FATAL_ERROR "saved JSON lacks positions/themes:\n${saved}")
endif()

# A second session: errors do not end the loop; EOF ends it with 0.
file(WRITE "${TABLES}/shell_errors.txt" "theme nosuch\nshow 0\nfrobnicate\ncount 1\n")
execute_process(COMMAND "${HELPMATE}" mine KQvk --dtm 2 --max 20 --interactive --tables "${TABLES}"
                INPUT_FILE "${TABLES}/shell_errors.txt"
                OUTPUT_VARIABLE out2 ERROR_VARIABLE err2 RESULT_VARIABLE rc2)
if(NOT rc2 EQUAL 0)
  message(FATAL_ERROR "error session exited ${rc2}")
endif()
foreach(p "unknown theme" "valid themes:" "no hit 0 \\(set has 20\\)" "unknown command \"frobnicate\"")
  if(NOT "${err2}" MATCHES "${p}")
    message(FATAL_ERROR "stderr lacks ${p}:\n${err2}")
  endif()
endforeach()
if(NOT "${out2}" MATCHES " positions\n$")
  message(FATAL_ERROR "count 1 did not run after the errors:\n${out2}")
endif()
message(STATUS "mine --interactive session verified")
