"""Render deepest_showcase.py's JSON into docs/DEEPEST.md.

The LaTeX booklet in tools/deepest_booklet.py reads the same JSON and shares
the diagram, link and notation code in tools/deepest_lib.py, so the two
renderings never drift apart.
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from deepest_lib import helpman_url, hn, numbered, numbers, ordered, piece_counts, svg_diagram  # noqa: E402


def card(r: dict, n: int, img: str) -> str:
    """One problem as a two-column HTML card: diagram left, everything else
    right. Plain HTML, not markdown, because GitHub does not parse markdown
    inside table cells; and only the attributes GitHub keeps (width, valign)."""
    w, b = piece_counts(r["fen"])
    g = r["max_dtm"] - r["dtm"]
    sat = (" Every position at that depth is saturated (255+ solutions)."
           if r["saturated_at_max"] else "")
    plural = "s" if r["unique_at_depth"] != 1 else ""
    of_total = (f" of {r['plane_size']:,} indexed" if r.get("plane_size") else "")
    themes = r.get("themes") or []
    tags = " ".join(f"<code>{t}</code>" for t in themes) if themes else "<i>none detected</i>"
    return "\n".join([
        "<table><tr>",
        f'<td width="220" valign="top"><img src="{img}" width="200" alt="{r["material"]}, {hn(r["dtm"])}">'
        f"<br><sub><b>{hn(r['dtm'])}</b> &nbsp;·&nbsp; {w} + {b}</sub></td>",
        '<td valign="top">',
        f"<b>No. {n}</b> &nbsp;·&nbsp; <b>{hn(r['dtm'])}</b>, unique solution &nbsp;·&nbsp; "
        f'<a href="{helpman_url(r["fen"], r["dtm"])}">solve ↗</a><br>',
        f"{r['unique_at_depth']:,} position{plural}{of_total} {'have' if plural else 'has'} a unique "
        f"solution at {hn(r['dtm'])}. The class runs to {hn(r['max_dtm'])}, so the deepest sound "
        f"problem is {g} pl{'y' if g == 1 else 'ies'} shallower.{sat}<br>",
        f"<br><b>Solution:</b> {numbered(r['solution'], r['dtm'])}<br>",
        f"<br><b>Themes:</b> {tags}<br>",
        f"<br><code>{r['fen']}</code>",
        "</td>",
        "</tr></table>",
    ])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--out", default="docs/DEEPEST.md")
    ap.add_argument("--images", default=None,
                    help="directory for the per-class SVG diagrams "
                         "(default: images/deepest next to --out)")
    a = ap.parse_args()
    rows = json.loads(Path(a.data).read_text())
    gaps = [r["max_dtm"] - r["dtm"] for r in rows]
    sat = sum(1 for r in rows if r["saturated_at_max"])
    lone = sum(1 for r in rows if r["unique_at_depth"] == 1)
    widest = max(rows, key=lambda r: r["max_dtm"] - r["dtm"])
    deepest = max(rows, key=lambda r: r["dtm"])

    L: list[str] = []
    L.append("# The deepest sound problem in every material class\n")
    L.append(f"""One position per material: the deepest position with a **unique solution**.

In problem chess uniqueness is the quality criterion. A second solution is a
dual and the composition is unsound, so `count = 1` is what makes a position
worth anything as a problem.

**The deepest problem in a material class is almost never the longest one.**
Across all {len(rows)} classes here, the deepest *unique* position is shallower
than the class maximum **every single time** — {len(rows)}/{len(rows)}, mean gap
{statistics.mean(gaps):.1f} plies, worst case {max(gaps)}. The reason is visible
in the data: in {sat} of {len(rows)} classes every position at maximum depth has a
**saturated** solution count (255 or more). The longest helpmates have hundreds
of ways to reach mate, which is exactly what disqualifies them as compositions.

The extreme case is **{widest['material']}**: it runs to {hn(widest['max_dtm'])},
but its deepest sound problem is {hn(widest['dtm'])} — {max(gaps)} plies shallower.

These positions are also rare. {lone} classes contain **exactly one** unique
position at their deepest sound depth; {sum(1 for r in rows if r['unique_at_depth'] <= 10)}
contain ten or fewer.

Black moves first and cooperates. `h#n` means mate after n moves by each side;
`h#n.5` means White is to move and needs one extra half-move. Under each
diagram stands the stipulation and the material count, white men + black men;
each problem carries its number (the same one as in the booklet), the themes it
shows (see the [theme catalogue](THEME-CATALOG.md)), and a *solve* link that
opens it in the Helpmate Analyzer with the stipulation set. The piece drawings
are Cburnett's (Wikimedia Commons, CC BY-SA 3.0).

Generated by [`tools/deepest_showcase.py`](../tools/deepest_showcase.py) and
rendered by [`tools/render_deepest.py`](../tools/render_deepest.py) — nothing here
is hand-written. Depths and position counts come from each table's exact
`uniqueness` histogram, not from sampling; every FEN is verified by probing
before it is used.

The same data is also typeset as a print booklet:
[`docs/DEEPEST.tex`](DEEPEST.tex), built by
[`tools/deepest_booklet.py`](../tools/deepest_booklet.py).\n""")
    L.append(f"Deepest sound problem in the whole corpus: **{hn(deepest['dtm'])}** "
             f"({deepest['material']}, {deepest['unique_at_depth']} such position"
             f"{'s' if deepest['unique_at_depth'] != 1 else ''}).\n")

    L.append("## Index\n")
    L.append("Sorted by how deep a *sound* problem gets. `class max` is the longest "
             "helpmate in that material at any solution count.\n")
    L.append("| material | pieces | deepest sound | class max | gap | unique positions there |")
    L.append("| --- | --- | --- | --- | --- | --- |")
    for r in sorted(rows, key=lambda r: (-r["dtm"], r["material"])):
        g = r["max_dtm"] - r["dtm"]
        L.append(f"| [{r['material']}](#{r['material'].lower()}) | {r['pieces']} "
                 f"| **{hn(r['dtm'])}** | {hn(r['max_dtm'])} | −{g} | {r['unique_at_depth']:,} |")
    L.append("")

    out_path = Path(a.out)
    images = Path(a.images) if a.images else out_path.parent / "images" / "deepest"
    images.mkdir(parents=True, exist_ok=True)
    nums = numbers(rows)
    for r in ordered(rows):
        (images / f"{r['material']}.svg").write_text(svg_diagram(r["fen"]))
        L.append(f"## {r['material']}\n")
        L.append(card(r, nums[r["material"]],
                      f"{images.name and images.relative_to(out_path.parent)}/{r['material']}.svg"))
        L.append("")

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
