"""Render deepest_showcase.py's JSON into docs/DEEPEST.md.

The LaTeX booklet in tools/deepest_booklet.py reads the same JSON and shares
the diagram, link and notation code in tools/deepest_lib.py, so the two
renderings never drift apart.
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from deepest_lib import diagram, helpman_url, hn, numbered  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--out", default="docs/DEEPEST.md")
    a = ap.parse_args()
    rows = json.loads(Path(a.data).read_text())
    gaps = [r["max_dtm"] - r["dtm"] for r in rows]
    sat = sum(1 for r in rows if r["saturated_at_max"])
    lone = sum(1 for r in rows if r["unique_at_depth"] == 1)
    widest = max(rows, key=lambda r: r["max_dtm"] - r["dtm"])
    deepest = max(rows, key=lambda r: r["dtm"])

    L: list[str] = []
    L.append("# The deepest sound problem in every material class\n")
    L.append(f"""One position per material: the deepest position with a **unique solution**.

In problem chess uniqueness is the quality criterion. A second solution is a
dual and the composition is unsound, so `count = 1` is what makes a position
worth anything as a problem.

**The deepest problem in a material class is almost never the longest one.**
Across all {len(rows)} classes here, the deepest *unique* position is shallower
than the class maximum **every single time** — {len(rows)}/{len(rows)}, mean gap
{statistics.mean(gaps):.1f} plies, worst case {max(gaps)}. The reason is visible
in the data: in {sat} of {len(rows)} classes every position at maximum depth has a
**saturated** solution count (255 or more). The longest helpmates have hundreds
of ways to reach mate, which is exactly what disqualifies them as compositions.

The extreme case is **{widest['material']}**: it runs to {hn(widest['max_dtm'])},
but its deepest sound problem is {hn(widest['dtm'])} — {max(gaps)} plies shallower.

These positions are also rare. {lone} classes contain **exactly one** unique
position at their deepest sound depth; {sum(1 for r in rows if r['unique_at_depth'] <= 10)}
contain ten or fewer.

Black moves first and cooperates. `h#n` means mate after n moves by each side;
`h#n.5` means White is to move and needs one extra half-move. Diagrams are in
the Popeye convention: `-` marks a black man and `S` is the knight. Under each
board stands the stipulation and the material count, white men + black men.

Generated by [`tools/deepest_showcase.py`](../tools/deepest_showcase.py) and
rendered by [`tools/render_deepest.py`](../tools/render_deepest.py) — nothing here
is hand-written. Depths and position counts come from each table's exact
`uniqueness` histogram, not from sampling; every FEN is verified by probing
before it is used.

The same data is also typeset as a print booklet:
[`docs/DEEPEST.tex`](DEEPEST.tex), built by
[`tools/deepest_booklet.py`](../tools/deepest_booklet.py).\n""")
    L.append(f"Deepest sound problem in the whole corpus: **{hn(deepest['dtm'])}** "
             f"({deepest['material']}, {deepest['unique_at_depth']} such position"
             f"{'s' if deepest['unique_at_depth'] != 1 else ''}).\n")

    L.append("## Index\n")
    L.append("Sorted by how deep a *sound* problem gets. `class max` is the longest "
             "helpmate in that material at any solution count.\n")
    L.append("| material | pieces | deepest sound | class max | gap | unique positions there |")
    L.append("| --- | --- | --- | --- | --- | --- |")
    for r in sorted(rows, key=lambda r: (-r["dtm"], r["material"])):
        g = r["max_dtm"] - r["dtm"]
        L.append(f"| [{r['material']}](#{r['material'].lower()}) | {r['pieces']} "
                 f"| **{hn(r['dtm'])}** | {hn(r['max_dtm'])} | −{g} | {r['unique_at_depth']:,} |")
    L.append("")

    for r in sorted(rows, key=lambda r: (r["pieces"], r["material"])):
        g = r["max_dtm"] - r["dtm"]
        L.append(f"## {r['material']}\n")
        note = (" — every position at that depth is saturated (255+ solutions)"
                if r["saturated_at_max"] else "")
        L.append(f"**{hn(r['dtm'])}**, unique solution. The class runs to "
                 f"{hn(r['max_dtm'])}{note}, so the deepest *sound* problem is "
                 f"{g} pl{'y' if g == 1 else 'ies'} shallower.\n")
        plural = "s" if r["unique_at_depth"] != 1 else ""
        of_total = (f", out of {r['plane_size']:,} indexed positions"
                    if r.get("plane_size") else "")
        L.append(f"{r['unique_at_depth']:,} position{plural} in this class "
                 f"{'have' if plural else 'has'} a unique solution at "
                 f"{hn(r['dtm'])}{of_total}.\n")
        L.append("```")
        L.append(diagram(r["fen"], r["dtm"]))
        L.append("```\n")
        L.append(f"`{r['fen']}`\n")
        L.append(f"Solution: `{numbered(r['solution'], r['dtm'])}`\n")
        L.append(f"[Solve on the Helpmate Analyzer]({helpman_url(r['fen'], r['dtm'])})\n")

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
